
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_on_github:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maker: [make, cmake]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Test build
        run: maker=${{matrix.maker}} .github/workflows/script.sh
          
  
